djangoProject2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path('', main_page),
    path('signup/', SignUpView.as_view()),
    path('catalog/', product_list, name='product_list'),
    path('catalog/<str:category_slug>/', product_list, name='product_list_by_category'),
    path('catalog/<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('about/', about),
    path('contact/', contact),
    path('cart/', cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('orders/create/', order_create, name='order_create'),
    path('coupons/apply/', coupon_apply, name='apply')
]

templates/product/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Продукты{% endif %}
{% endblock %}
{% block content %}
    <div class="d-flex flex-column align-items-center border p-5">
        <img class="shadow"  width="30%" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2 >Категория: <a class="text-decoration-none text-dark" href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>

<form action="{% url "main:cart_add" product.id %}" method="post">
    <div class="d-flex flex-column">
        <p class="btn btn-outline-secondary p-1">${{ product.price }}</p>
    {{ cart_product_form|crispy }}
    </div>

    {% csrf_token %}
    <div class="d-grid gap-2">
         <input class="btn btn-success"  type="submit" value="Add to cart">
    </div>

</form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

templates/product/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

    <div>
        <h3 class="text-center">Категории</h3>
        <ul class="nav nav-pills nav-fill">

            {% for c in categories %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ c.get_absolute_url }}"><img class="h-75" src="{{ c.img.url }}"/></a>

                </li>
            {% endfor %}
        </ul>

    </div>
    <div>
        <h3 class="text-center my-3">{% if category %}{{ category.name }}{% else %}Продукты{% endif %}</h3>
    {% for product in products %}
    <div class="row row-cols-1 row-cols-md-3 mb-3 d-flex justify-content-around text-center">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-body">

            <ul class="list-unstyled ">
              <a class="" href="{{ product.get_absolute_url }}"><img class="card-img" src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}"></a>
            </ul>
              <a class="w-100 btn btn-lg opacity-75" href="{{ product.get_absolute_url }}"><h4 class="text-dark my-0 fw-normal">{{ product.name }}</h4></a>
              <h1 class="card-title pricing-card-title">{{ product.price }}<small class="text-muted fw-light">RUB</small></h1>
            <a href="{{ product.get_absolute_url }}" type="button" class="w-100 btn btn-lg btn-secondary" formaction="">Перейти к товару</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>
{% endblock %}