djangoProject2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path('', main_page),
    path('signup/', SignUpView.as_view()),
    path('catalog/', product_list, name='product_list'),
    path('catalog/<str:category_slug>/', product_list, name='product_list_by_category'),
    path('catalog/<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('about/', about),
    path('contact/', contact),
    path('cart/', cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('orders/create/', order_create, name='order_create'),
    path('coupons/apply/', coupon_apply, name='apply')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="container bg-light">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><img class="w-50" src="{% static 'main_page/logo.png' %}" alt="logo"/></a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-uppercase" href="/catalog">Каталог</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-uppercase" href="/about">О нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-uppercase" href="/contact">Контакты</a>
                </li>
            </ul>
        </div>


        <div class="mx-3">
            {% with total_items=cart|length %}

                {% if cart %}
                    <a class="btn border rounded-3" href="{% url "main:cart_detail" %}">
                        <svg xmlns="http://www.w3.org/2000/svg" height="40px" fill="currentColor" class="bi bi-cart2"
                             viewBox="0 0 16 16">
                            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                            <span class="border-danger">{{ total_items }}</span>
                        </svg>
                    </a>
                {% endif %}
            {% endwith %}
        </div>


        {% if user.is_authenticated %}
            <div class="dropdown text-end">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle " id="dropdownUser1"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small " aria-labelledby="dropdownUser1"
                    style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 34px);"
                    data-popper-placement="bottom-start">
                    <li><a class="dropdown-item" href="#">New project...</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="/accounts/logout/">Sign out</a></li>
                </ul>
            </div>
        {% else %}
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="btn text-uppercase" href="/accounts/login">Sign-in</a>
                    </li>

                    <li class="nav-item">
                        <a class="text-uppercase btn btn-primary" href="/signup">Sign-up</a>
                    </li>
                </ul>
            </div>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>

</nav>

{% block content %}
    <a href="/catalog"><img alt="slider" class="img-fluid w-100" src="{% static 'main_page/slider.jpg' %} "/></a>
    <div class="d-flex flex-wrap justify-content-around">
        {% for c in categories %}
            <div class="my-5 shadow">
                <a href="{{ c.get_absolute_url }}"><img src="{{ c.img.url }}"/></a>
            </div>



        {% endfor %}
    </div>
{% endblock %}

<div class="">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-muted">&copy; 2022 Company, Inc</p>

        <a href="/"
           class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
            <img src="{% static 'main_page/logo.png' %}" class="w-25"/>


        </a>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="catalog/" class="nav-link px-2 text-muted">Каталог</a></li>
            <li class="nav-item"><a href="about/" class="nav-link px-2 text-muted">О нас</a></li>
            <li class="nav-item"><a href="/contact" class="nav-link px-2 text-muted">Контакты</a></li>
        </ul>
    </footer>
</div>
<script src="{% static 'bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>